/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.test.demo.controller.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Abc service. Represents a row in the &quot;xyz&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.demo.controller.model.impl.AbcModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.demo.controller.model.impl.AbcImpl}.
 * </p>
 *
 * @author shatrusudan.sharma
 * @see Abc
 * @see com.test.demo.controller.model.impl.AbcImpl
 * @see com.test.demo.controller.model.impl.AbcModelImpl
 * @generated
 */
public interface AbcModel extends AuditedModel, BaseModel<Abc> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a abc model instance should use the {@link Abc} interface instead.
	 */

	/**
	 * Returns the primary key of this abc.
	 *
	 * @return the primary key of this abc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this abc.
	 *
	 * @param primaryKey the primary key of this abc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the foo ID of this abc.
	 *
	 * @return the foo ID of this abc
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this abc.
	 *
	 * @param fooId the foo ID of this abc
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the company ID of this abc.
	 *
	 * @return the company ID of this abc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this abc.
	 *
	 * @param companyId the company ID of this abc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this abc.
	 *
	 * @return the user ID of this abc
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this abc.
	 *
	 * @param userId the user ID of this abc
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this abc.
	 *
	 * @return the user uuid of this abc
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this abc.
	 *
	 * @param userUuid the user uuid of this abc
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this abc.
	 *
	 * @return the user name of this abc
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this abc.
	 *
	 * @param userName the user name of this abc
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this abc.
	 *
	 * @return the create date of this abc
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this abc.
	 *
	 * @param createDate the create date of this abc
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this abc.
	 *
	 * @return the modified date of this abc
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this abc.
	 *
	 * @param modifiedDate the modified date of this abc
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this abc.
	 *
	 * @return the field1 of this abc
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this abc.
	 *
	 * @param field1 the field1 of this abc
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this abc.
	 *
	 * @return the field2 of this abc
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this abc is field2.
	 *
	 * @return <code>true</code> if this abc is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this abc is field2.
	 *
	 * @param field2 the field2 of this abc
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this abc.
	 *
	 * @return the field3 of this abc
	 */
	public int getField3();

	/**
	 * Sets the field3 of this abc.
	 *
	 * @param field3 the field3 of this abc
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this abc.
	 *
	 * @return the field4 of this abc
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this abc.
	 *
	 * @param field4 the field4 of this abc
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this abc.
	 *
	 * @return the field5 of this abc
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this abc.
	 *
	 * @param field5 the field5 of this abc
	 */
	public void setField5(String field5);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Abc abc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Abc> toCacheModel();

	@Override
	public Abc toEscapedModel();

	@Override
	public Abc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}