/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.workflow.demo.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.workflow.demo.model.Feedback;
import com.workflow.demo.service.FeedbackLocalServiceUtil;

/**
 * The extended model base implementation for the Feedback service. Represents a row in the &quot;test_Feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeedbackImpl}.
 * </p>
 *
 * @author shatrusudan
 * @see FeedbackImpl
 * @see com.workflow.demo.model.Feedback
 * @generated
 */
public abstract class FeedbackBaseImpl extends FeedbackModelImpl
	implements Feedback {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feedback model instance should use the {@link Feedback} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FeedbackLocalServiceUtil.addFeedback(this);
		}
		else {
			FeedbackLocalServiceUtil.updateFeedback(this);
		}
	}
}